/* COURSES Table inserts */
INSERT INTO PROFESSORS(ID, NAME, EMAIL) VALUES (1, 'Juan Peréz', 'juan@mail.com');
INSERT INTO PROFESSORS(ID, NAME, EMAIL) VALUES (2, 'Pedro Rodríguez', 'pedro@mail.com');
INSERT INTO PROFESSORS(ID, NAME, EMAIL) VALUES (3, 'Carlos Gutierrez', 'carlos@mail.com');
INSERT INTO PROFESSORS(ID, NAME, EMAIL) VALUES (4, 'Roberto Fernandez', 'roberto@mail.com');
INSERT INTO PROFESSORS(ID, NAME, EMAIL) VALUES (5, 'Andrés Peréz', 'andres@mail.com');


/* EMPLOYEES Table inserts */
INSERT INTO COURSES(TITLE,LEVEL,HOURS,ACTIVE,PROFESSOR_ID) VALUES ('Introduction to Java', 'BASIC', 200, true, 1);
INSERT INTO COURSES(TITLE,LEVEL,HOURS,ACTIVE,PROFESSOR_ID) VALUES ('Test-Driven Development', 'ADVANCED', 324, true, 4);
INSERT INTO COURSES(TITLE,LEVEL,HOURS,ACTIVE,PROFESSOR_ID) VALUES ('Learn Python', 'BASIC', 134, true, 3);
INSERT INTO COURSES(TITLE,LEVEL,HOURS,ACTIVE,PROFESSOR_ID) VALUES ('OOP', 'BASIC', 200, true, 4);
INSERT INTO COURSES(TITLE,LEVEL,HOURS,ACTIVE,PROFESSOR_ID) VALUES ('Design Pattern', 'ADVANCED', 130, true, 5);
INSERT INTO COURSES(TITLE,LEVEL,HOURS,ACTIVE,PROFESSOR_ID) VALUES ('Java Frameworks', 'ADVANCED', 230, true, 5);