CREATE TABLE PROFESSORS (
  ID                  INT PRIMARY KEY,
  NAME                VARCHAR(250) NOT NULL,  
  EMAIL               VARCHAR(100) NOT NULL  
);

CREATE TABLE COURSES (
  ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE               VARCHAR(250) NOT NULL,  
  LEVEL               VARCHAR(55) NOT NULL,
  HOURS               INT NOT NULL,
  ACTIVE              BOOLEAN DEFAULT TRUE NOT NULL,
  PROFESSORS_ID       INT NOT NULL
);

ALTER TABLE COURSES ADD FOREIGN KEY (PROFESSORS_ID) REFERENCES PROFESSORS(ID);
ALTER TABLE COURSES ADD CONSTRAINT COURSES_UNIQUE UNIQUE (TITLE, LEVEL);